# Use the official NGINX image
FROM nginx:alpine

# Copy the custom nginx configuration file into the container
COPY nginx.conf /etc/nginx/nginx.conf

# Expose port 80 to allow access to NGINX
EXPOSE 80